exp: MinimalPair

mode:
  - train

models:
  hf_causal_model:
    - distilbert/distilgpt2

# Train
trainfpath: ../cosc426/hw/hw03/data/train.tsv

validfpath: ../cosc426/hw/hw03/data/val.tsv

modelfpath: ../cosc426/hw/hw03/models/distilgpt2

loadPretrained: False
