exp: MinimalPair

mode: 
    - evaluate
    - analyze

models: 
      hf_causal_model:
          - distilbert/distilgpt2

datafpath: stim.tsv

predfpath: predictions.tsv

resultsfpath: results.tsv

pred_measure: prob

