# Bayesian - negative
exp: MinimalPair

mode:
  - evaluate

models:
  hf_causal_model:
    - /Users/jeong/Projects/cosc426-projects/cosc426/hw/hw04/models/neg_bay

predfpath: ../cosc426/hw/hw04/predictions/neg_predictions.tsv

datafpath: ../cosc426/hw/hw04/data/bay_eval.tsv

save: by_cond
