# Eval cuda_textclassification
exp: TextClassification

mode:
  - evaluate
  - analyze

models:
  hf_text_classification_model:
    - /Users/jeong/Projects/cosc426-projects/cosc426/hw/hw04/models/cuda_textclassification

predfpath: ../cosc426/hw/hw04/predictions/cuda_textclassification.tsv

datafpath: ../cosc426/hw/hw04/data/textclassification_eval.tsv

resultsfpath: ../cosc426/hw/hw04/results/cuda_textclassification.tsv

save: by_cond, by_target

id2label:
  0: neg
  1: pos
