# Trains Textclassification
exp: TextClassification

mode:
  - train

models:
  hf_causal_model:
    - distilbert/distilgpt2

trainfpath: ../cosc426/hw/hw04/data/textclassification_train.tsv

validfpath: ../cosc426/hw/hw04/data/textclassification_val.tsv

modelfpath: ../cosc426/hw/hw04/models/textclassification

loadPretrained: True
