exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_causal_model:
    - distilbert/distilgpt2

predfpath: ../cosc426/hw/hw01/predictions/predictions.tsv

datafpath: ../cosc426/hw/hw01/data/data.tsv

resultsfpath: ../cosc426/hw/hw01/results/results.tsv

conditions: bias, frequency

pred_measure: prob

save: by_pair, by_cond
